const data = [
  {
    id: 1,
    name: 'giant Pandas',
    title: 'Native to Southwest China',
    image: './src/img/animals/giant Pandas.jpg',
    icon: './src/img/icon-slaider/banana-bamboo.svg',
  },
  {
    id: 2,
    name: 'Eagles',
    title: 'Native to South America',
    image: './src/img/animals/Eagles.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 3,
    name: 'Gorillas',
    title: 'Native to Cong',
    image: './src/img/animals/Gorillas.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 4,
    name: 'Two-toed Sloth',
    title: 'Mesoamerica, South America',
    image: './src/img/animals/Two-toed Sloth.jpg',
    icon: './src/img/icon-slaider/banana-bamboo.svg',
  },
  {
    id: 5,
    name: 'cheetahs',
    title: 'Native to Africa',
    image: './src/img/animals/cheetahs.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 6,
    name: 'Penguins',
    title: 'Native to Antarctica',
    image: './src/img/animals/Penguins.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 7,
    name: 'crane',
    title: 'Native to North America',
    image: './src/img/animals/crane.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 8,
    name: 'echidna',
    title: 'Native to Australia',
    image: './src/img/animals/Echidna.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 9,
    name: 'hippopotamus',
    title: 'Native to Africa',
    image: './src/img/animals/hippopotamus.jpg',
    icon: './src/img/icon-slaider/banana-bamboo.svg',
  },
  {
    id: 10,
    name: 'lynx',
    title: 'Native to Canada',
    image: './src/img/animals/lynx.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 11,
    name: 'Musang',
    title: 'Native to Asia',
    image: './src/img/animals/Musang.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 12,
    name: 'Ocelot',
    title: 'Native to Asia',
    image: './src/img/animals/Ocelot.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 13,
    name: 'owl',
    title: 'Native to Europe',
    image: './src/img/animals/owl.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 14,
    name: 'Red wolf',
    title: 'Native to Southeast USA',
    image: './src/img/animals/Red wolf.jpg',
    icon: './src/img/icon-slaider/meet-fish.svg',
  },
  {
    id: 15,
    name: 'bison',
    title: 'Native to Europe',
    image: './src/img/animals/bison.jpg',
    icon: './src/img/icon-slaider/banana-bamboo.svg',
  }
];

export default data;